#
# version: '3'
# https://github.com/compose-spec/compose-spec/blob/master/spec.md
#
# run the WebSocket.yml file
#     docker compose -f WebSocket.yml --project-name wss up [-d]
#
# to terminate the container, hit CTRL-C
#
# docker run -it --rm --name wss --hostname wss \
# --domainname example.com --ip 172.31.10.20 \
# -p 9443:6443 -p 9080:6080 \
# --mount type=bind,source="$(pwd)",target=/run \
# -w /run --network frontend node:current-alpine /bin/sh

# https://stackoverflow.com/questions/50947938/docker-compose-orphan-containers-warning

networks:
   frontend:
      name: frontend

services:
  WebSocket:
    image: node:current-alpine
    working_dir: /run
    command: npm run dev
    volumes:
      - type: bind
        source: $PWD
        # source: $PWD/server
        target: /run
    ports:
      - "9080:6080"
      - "9443:6443"
    restart: "no"
    environment:
      - WS_PORT=6080
      - WSS_PORT=6443
    hostname: wss
    container_name: wss
    domainname: example.com
    networks:
      frontend:
        ipv4_address: 172.31.10.20
